activemq:
  broker-url: tcp://192.168.99.100:61616
  user: user1
  password: jmx_password

# Propiedades para usar la configuracion por defecto que proporciona el starter
#spring:
#  activemq:
#    broker-url: tcp://192.168.99.100:61616
#    user: user1
#    password: jmx_password